export const LANGUAGES =  [
    "English",
    "Thai",
    "Vietnamese",
    "Tagalog",
    "Korean",
    "Japanese",
    "Mandarin",
    "Burmese",
    "Malay",
    "Bahasa Indonesia",
    "Spanish",
    "Portuguese",
    "Russian",
    "German",
    "French",
    "Italian",
    "Turkish",
    "Polish",
    "Ukrainian",
    "Romanian",
    "Dutch",
    "Croatian",
    "Hungarian",
    "Greek",
    "Czech",
    "Swedish",
    "Hindi",
    "Arabic",
    "Bengali",
    "Punjabi",
    "Tamil",
    "Urdu",
    "Gujarati",
    "Persian"
  ];

  export const DESTINATIONS =  [
    "Bali",
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Makassar",
    "Barcelona",
    "London",
  ];